#!/bin/sh

# sh -c "$(curl -fsSL https://dotfiles.ajai.dev/download)"
# sh -c "$(wget -qO - https://dotfiles.ajai.dev/download)"
# TODO: maybe https://stackoverflow.com/a/72601010

# Truncation guard
if : ; then
	set -eu
	set -x

	umask go-rwx

	confirm() {
		set +x
		printf '%s (y/n) ' "$1"
		read -r REPLY </dev/tty
		case "$REPLY" in
			y*) : ;;
			Y*) : ;;
			*) return 2 ;;
		esac
		set -x
	}

	if ! [ -e "${DOTFILES:=$HOME/prog/dotfiles}" ]; then
		mkdir -p "$(dirname "$DOTFILES")"
		cd "$(dirname "$DOTFILES")"
		echo "Installing to $DOTFILES..."
		if command -v git >/dev/null 2>&1 && [ -z "${NO_GIT:-}" ]; then
			git clone --depth=1 "https://github.com/AjaiKN/dotfiles"
		else
			set +x; confirm "There's no git command in PATH. Use wget/curl instead?" || exit 2

			if command -v wget >/dev/null 2>&1; then
				wget 'https://github.com/AjaiKN/dotfiles/releases/latest/download/dotfiles.tar.gz'
			elif command -v curl >/dev/null 2>&1; then
				curl -LO 'https://github.com/AjaiKN/dotfiles/releases/latest/download/dotfiles.tar.gz'
			else
				echo "no curl or wget command available in PATH"
				exit 2
			fi

			mkdir -p "$DOTFILES"
			if command -v tar >/dev/null 2>&1; then
				tar -x -f dotfiles.tar.gz -k -C "$DOTFILES" --strip-components=1
			elif command -v bsdtar >/dev/null 2>&1; then
				bsdtar -x -f dotfiles.tar.gz -k -C "$DOTFILES" --strip-components=1
			else
				echo "no tar command available in PATH"
				exit 2
			fi
		fi
	fi

	if [ -e "$DOTFILES"/install ]; then
		set +x
		if confirm "Dotfiles are downloaded to $DOTFILES. Install to home directory now?"; then
			exec "$DOTFILES"/install -v
		else
			echo "To install, run:"
			echo "$DOTFILES/install -v"
		fi
	else
		echo "Failed to download"
		exit 1
	fi
fi
