#!/bin/sh

set -eu

confirm() {
	printf '%s (y/n) ' "$1"
	read -r REPLY
	case "$REPLY" in
		y*) : ;;
		*) return 2 ;;
	esac
}

DOTFILES=$(realpath "$(dirname "$0")")
export DOTFILES

umask 077

cd "$DOTFILES"

no_submodules_update=
for arg in "$@"; do
	if [ "$arg" = '--no-submodules-update' ]; then
		no_submodules_update=1
	fi
done
if [ -z "$no_submodules_update" ]; then
	echo "Updating submodules..."
	./submodules-update.sh || :
fi

echo "Installing files..."
./install-files.sh --no-submodules-update "$@"

if [ ! -e ~/.gitconfig ]; then
	(
		set -x
		touch ~/.gitconfig
	)
fi

if [ "$(uname -s)" = "Darwin" ]; then
	echo
	if [ -e "$HOME/.local/state/akn-dotfiles-confirmed-install-defaults" ] || confirm "Do you want to install my macOS defaults? This can't be undone by the uninstall script."; then
		echo "Setting macOS defaults..."
		./install-defaults.mac.sh
		if ! [ -e "$HOME/.local/state/akn-dotfiles-confirmed-install-defaults" ]; then
			echo
			echo "In the future, my macOS defaults will always be installed without asking when you run this script. If you don't want that, delete the file $HOME/.local/state/akn-dotfiles-confirmed-install-defaults"
			mkdir -p "$HOME/.local/state"
			touch "$HOME/.local/state/akn-dotfiles-confirmed-install-defaults"
		fi
	fi
fi

echo
echo "Setting permissions..."
./install-permissions.sh
