#!/bin/sh

set -eu

confirm() {
	printf '%s (y/n) ' "$1"
	read -r REPLY
	case "$REPLY" in
		y*) : ;;
		*) return 2 ;;
	esac
}

DOTFILES=$(realpath "$(dirname "$0")")
case $DOTFILES in
	/gnu/*)
		if [ -d "$HOME/prog/dotfiles" ]; then
			DOTFILES="$HOME/prog/dotfiles"
		fi
		;;
esac
export DOTFILES

umask 077

cd "$DOTFILES"

no_submodules_update=
for arg in "$@"; do
	if [ "$arg" = '--no-submodules-update' ]; then
		no_submodules_update=1
	fi
done
if [ -z "$no_submodules_update" ]; then
	echo "Updating submodules..."
	./submodules-update.sh || :
fi

echo
echo "Installing files..."
./install-files.sh --no-submodules-update "$@"

if [ ! -e ~/.gitconfig ]; then
	(
		set -x
		touch ~/.gitconfig
	)
fi

if [ "$(uname -s)" = "Darwin" ]; then
	echo
	echo "Setting macOS defaults..."
	./install-defaults.mac.sh
fi

echo
echo "Setting permissions..."
./install-permissions.sh
