#!/bin/sh

set -eu

DOTFILES=$(realpath "$(dirname "$0")")
export DOTFILES

umask go-rwx

cd "$DOTFILES"

confirm() {
	printf '%s (y/n) ' "$1"
	read -r REPLY
	case "$REPLY" in
		y*) : ;;
		*) return 2 ;;
	esac
}

./install-dot-home.sh "$@"

if [ ! -e ~/.gitconfig ]; then
	touch ~/.gitconfig
fi

if [ "$(uname -s)" = "Darwin" ]; then
	echo
	if [ -e "$HOME/.local/state/akn-dotfiles-confirmed-install-defaults" ] || confirm "Do you want to install my macOS defaults? This can't be undone by the uninstall script."; then
		./install-defaults.mac.sh
		if ! [ -e "$HOME/.local/state/akn-dotfiles-confirmed-install-defaults" ]; then
			echo
			echo "In the future, my macOS defaults will always be installed without asking when you run this script. If you don't want that, delete the file $HOME/.local/state/akn-dotfiles-confirmed-install-defaults"
			mkdir -p "$HOME/.local/state"
			touch "$HOME/.local/state/akn-dotfiles-confirmed-install-defaults"
		fi
	fi
fi

echo
./install-permissions.sh
