#!/usr/bin/env bash

set -euo pipefail
# shellcheck disable=SC2154
trap 's=$?; echo >&2 ": Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

cd "$(dirname "$0")"
set -x

if [ -x "private/sync" ]; then
  private/sync
fi

git rev-parse HEAD
git fetch origin main
git merge --no-edit --autostash origin/main

./install
