#!/bin/sh

set -eu

DOTFILES=$(realpath "$(dirname "$0")")
case $DOTFILES in
	/gnu/*)
		if [ -d "$HOME/prog/dotfiles" ]; then
			DOTFILES="$HOME/prog/dotfiles"
		fi
		;;
esac
export DOTFILES
cd "$DOTFILES"

AKN_UNINSTALL=1 ./install-files.sh
