#!/bin/sh

set -eu

DOTFILES=$(realpath "$(dirname "$0")")
case $DOTFILES in
	/gnu/*)
		if [ -d "$HOME/prog/dotfiles" ]; then
			DOTFILES="$HOME/prog/dotfiles"
		fi
		;;
esac
export DOTFILES
cd "$DOTFILES"

export AKN_UNINSTALL=1

echo "Uninstalling files..."
./install-files.sh

if [ "$(uname -s)" = "Darwin" ]; then
	echo "Unsetting macOS defaults..."
	./install-defaults.mac.sh
fi
