#!/usr/bin/env bash

set -euo pipefail
# shellcheck disable=SC2154
trap 's=$?; echo >&2 ": Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
set -x

DOTFILES=$(realpath "$HOME/.dotfiles")
case $DOTFILES in
	/gnu/*)
		if [ -e "$HOME/prog/dotfiles" ]; then
			DOTFILES="$HOME/prog/dotfiles"
		fi
		;;
esac
export DOTFILES

"$DOTFILES"/uninstall

zap -f ~/.config/{atuin,emacs}
if [ -L ~/.dotfiles ]; then
	zap ~/.dotfiles
fi

guix home reconfigure "$DOTFILES/guix/home-configuration.scm"
