# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    login: auth login
    logout: auth logout
    alias create: alias set
    alias remove: alias delete
    co: pr checkout
    ls: list
    clone: repo clone
    fork: repo fork
    gitignore: repo gitignore
    license: repo license
    open: browse
    sync: repo sync
    view: repo view
    web: browse
    repo url: browse --no-browser
    url: repo url
    link: repo url
version: "1"
